### ISSUE TITLE
CobaltCause's to-do list

### ISSUE THREAD

**Issue by CobaltCause** [girlbossceo/conduwuit#321]
This is my personal to-do list of things that aren't worth having their own dedicated issue for. If you want to work on any of these things, please ask me first so we don't accidentally duplicate work. Expect this to be edited a lot over time.

* [ ] Yeet `stateres_mutex`
  * It does literally nothing, see [here](https://matrix.to/#/!n8DKU1BeeJilOJXDPr:seirdy.one/$o62qQlnaTQw_Ok8R8c7OIm7pT2S8AuYYM0VC6zpGTtM?via=girlboss.ceo&via=transfem.dev&via=matrix.org)
* [ ] Yeet `async-trait`
  * We're on Rust 1.75.0 (currently) so we have AFIT/RPITIT and thus don't need this anymore. Unless some dependency API depends on it...
* [ ] Refactor `src/main.rs`
  * It's kind of a mess and doesn't lend itself well to having multiple subcommands/entrypoints
* [ ] Add CLI to do DB compaction
  * Would be useful for taking offline backups
* [ ] Add CLI to yeet locally-uninhabited rooms from the DB
  * Would be useful for reclaiming disk space
* [ ] Improve error handling
  * `crate::utils::error::Error` makes me sad, and it makes various abstractions very leaky
