### ISSUE TITLE
0.5.0 release checklist

### ISSUE THREAD

**Issue by girlbossceo** [girlbossceo/conduwuit#454]
(maybe) Breaking stuff:
- [ ] Delete sqlite support (this has been a burden to maintain for something that we urge no one to use, isn't a default feature for a long time, and is a blocker to async database)
- [ ] Rename crate name from `conduit` to `conduwuit`

rustfmt.toml changes (huge diffs):
- [ ] Use `imports_layout = "HorizontalVertical"` or `imports_layout = "Vertical"`
- [ ] Change `max_width` to 100 from 120
- [ ] Revert/Delete `fn_params_layout = "Compressed"` to the default

**Comment by shishkin** [comment]
Is this list still accurate? What other things prevent 0.5.0 from happening?

I'm new to conduwuit, tried to install it on NixOS and building from source takes forever on a RPi. Somehow caches didn't help.
